server:
  port: 8888

#git上存放配置文件的地址
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raoshengx/eureka-config.git
          basedir: eureka-config
eureka:
  instance:
    appname: demo-config
